# Define the build version
version: 1.0.0-signed-{build}

image: Visual Studio 2022


environment:
  VERSION: v6.1.0
#  SIGNPATH_SIGNING_REQUEST_ID : "-" 
#  SIGNPATH_SIGNING_REQUEST_STATUS : "-"
#  SIGNPATH_ORGANIZATION_ID : 783237d7-f6db-4caa-b64e-a3fc87156006
  SIGNPATH_SIGNING_POLICY_SLUG: release-signing
  ARTIFACT_CONFIGURATION_SLUG: o2p2
  

#  SIGNPATH_CI_USER_TOKEN:
#    secure: fkMRmkT0HDBDna85gU5hTJnS4G7brD0xoc7YAtD001hqlRSgI4hCyCMtbeJZOYT1
 

install:
#  - choco install gh
  - ps: | 
      #Write-Host "install powershell modules"  
      # Install-Module -Name PowerShellForGitHub
      # Install-Module -Name SignPath   
      #dir env: >env.txt       
  

build_script:
  - ps: |    
       if ( $env:SIGNPATH_SIGNING_REQUEST_STATUS -eq "Completed") {  
         . ./run.ps1 
         Main './signed'
       } else {
         Write-Host "SIGNPATH_SIGNING_REQUEST_STATUS is not valid"
         exit 1
       }
    
artifacts:
- path: .\*.zip
  name: zip    
- path: .\sr.txt
  name: sr    
- path: .\signed\OData2Poco.dotnet.o2pgen*.nupkg
  name: global_tool
- path: .\signed\o2pgen.exe
  name: o2p_exe
- path: .\signed\OData2Poco.CommandLine.*.nupkg
  name: o2pgen
- path: .\signed\OData2Poco.*.nupkg
  name: lib 
- path: .\signed\OData2Poco.*.snupkg
  name: symbol 
- path: .\signed\OData2Poco-CommandLine.*.nupkg
  name: choco_pkg 

 
deploy:
#Github current repo   
- provider: GitHub
  auth_token: 
     secure: sB33uLo96nR+LGmYLdPmY/segb6d4O061N2e8Nbz6iyHg82D0RysMxWE5JKnXmU+
  artifact: zip,sr,global_tool,o2pgen,lib,symbol,choco_pkg,o2p_exe   
  force_update: true  
  prerelease: false  
  draft: true
  on:    
      SIGNING: true

#Github odata2poco repo
- provider: GitHub
  auth_token:
     secure: sB33uLo96nR+LGmYLdPmY/segb6d4O061N2e8Nbz6iyHg82D0RysMxWE5JKnXmU+
  artifact: global_tool,o2pgen,lib,symbol,choco_pkg,o2p_exe
  tag: $(VERSION)
  force_update: true  
  prerelease: false  
  draft: true
  repository: moh-hassan/odata2poco
  on:    
      SIGNING: true

# Nuget
- provider: NuGet
  api_key: $(NUGET_KEY)
  on:   
    SIGNING: true     
  artifact: global_tool,o2pgen,lib,symbol  

#chocolatey    
- provider: NuGet
  server: https://push.chocolatey.org   
  api_key: $(CHOCO_KEY) 
  on:   
    SIGNING: true    
  artifact: choco_pkg
  
# myget
- provider: NuGet
  server: https://www.myget.org/F/odata2poco/api/v3/
  api_key: $(MYGET_KEY)
  on:    
    SIGNING: true      
  artifact: global_tool,o2pgen,lib,symbol,choco_pkg
  
  
# init:
#   - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  
# on_finish:
#  - ps: $blockRdp = $true; iex ((new-object  net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

         