# Define the build version
version: 1.0.0-signed-{build}

image: Visual Studio 2022


environment:
  VERSION: v6.1.0
#  SIGNPATH_SIGNING_REQUEST_ID : "-" 
#  SIGNPATH_SIGNING_REQUEST_STATUS : "-"
#  SIGNPATH_ORGANIZATION_ID : 783237d7-f6db-4caa-b64e-a3fc87156006
  SIGNPATH_SIGNING_POLICY_SLUG: test-signing
  ARTIFACT_CONFIGURATION_SLUG: o2p2
  

#  SIGNPATH_CI_USER_TOKEN:
#    secure: fkMRmkT0HDBDna85gU5hTJnS4G7brD0xoc7YAtD001hqlRSgI4hCyCMtbeJZOYT1
 

install:
#  - choco install gh
  - ps: | 
      #Write-Host "install powershell modules"  
      # Install-Module -Name PowerShellForGitHub
      # Install-Module -Name SignPath   
      #dir env: >env.txt       
  

build_script:
  - ps: |      
       . ./run.ps1 
       Main
    
artifacts:
- path: .\*.zip
  name: zip    
- path: .\sr.txt
  name: sr    
- path: .\signed\OData2Poco.dotnet.o2pgen*.nupkg
  name: global_tool
- path: .\signed\o2pgen.exe
  name: o2p_exe
- path: .\signed\OData2Poco.CommandLine.*.nupkg
  name: o2pgen
- path: .\signed\OData2Poco.*.nupkg
  name: lib 
- path: .\signed\OData2Poco.*.snupkg
  name: pdp 
- path: .\signed\OData2Poco-CommandLine.*.nupkg
  name: choco_pkg 

 
deploy:
#Github    
- provider: GitHub
  auth_token:
     secure: sB33uLo96nR+LGmYLdPmY/segb6d4O061N2e8Nbz6iyHg82D0RysMxWE5JKnXmU+
  artifact: zip,sr   
  tag: $(VERSION)
  force_update: true  
  prerelease: false  
  draft: true
  on:    
      SIGNING: true

#Github 2    
- provider: GitHub
  auth_token:
     secure: sB33uLo96nR+LGmYLdPmY/segb6d4O061N2e8Nbz6iyHg82D0RysMxWE5JKnXmU+
  artifact: global_tool,o2pgen,lib,pdp,choco_pkg,o2p_exe
  tag: $(VERSION)
  force_update: true  
  prerelease: false  
  draft: false
  repository: moh-hassan/odata2poco2
  on:    
      SIGNING2: true

# myget
- provider: NuGet
  server: https://www.myget.org/F/odata2poco/api/v2/package
  api_key:
    secure: QAHjX2gqddFX2cNhMNqweMTGQ89q++ezKnQvdAcinY5D1rwbj2vkWeFsTykm4koA

  on:    
    SIGNING2: true      
  artifact: global_tool,o2pgen,lib,choco_pkg


# init:
#   - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  
# on_finish:
#  - ps: $blockRdp = $true; iex ((new-object  net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

         