# Define the build version
version: 6.3.3-signed-{build}

image: Visual Studio 2022


environment:  
  SIGNPATH_SIGNING_POLICY_SLUG: release-signing
  ARTIFACT_CONFIGURATION_SLUG: o2p2


# init:
#   - ps: |     
#       $ver = $env:REPO_TAG_NAME	  
#       try
#         {         
#           Update-AppveyorBuild -Version $ver 
#           Write-Host "Update-AppveyorBuild Success to change version to TAG: '$env:REPO_TAG_NAME'"   -ForegroundColor Green          
#         }
#         catch
#         {
#           Write-Host "Update-AppveyorBuild Fail to change version to TAG: '$env:REPO_TAG_NAME'"   -ForegroundColor Red
#           Write-Host "Exception Error: $PSItem.Exception.Message" -ForegroundColor Red
#           #$env:CAN_PUBLISH = $false
#         }
#        Write-Host "REPO_TAG_NAME= '$env:REPO_TAG_NAME'" -ForegroundColor Yellow         

build_script:
  - ps: |          
         . ./run.ps1 
         Main './signed'       
    
artifacts:
- path: .\*.zip
  name: zip    
- path: .\sr.txt
  name: sr    
- path: .\signed\OData2Poco.dotnet.o2pgen*.nupkg
  name: global_tool
- path: .\signed\o2pgen.exe
  name: o2p_exe
- path: .\signed\OData2Poco.CommandLine.*.nupkg
  name: o2pgen
- path: .\signed\OData2Poco.*.nupkg
  name: lib 
- path: .\signed\OData2Poco-CommandLine.*.nupkg
  name: choco_pkg 

 
# deploy:
# #Github current repo   
# - provider: GitHub
#   auth_token: 
#      secure: sB33uLo96nR+LGmYLdPmY/segb6d4O061N2e8Nbz6iyHg82D0RysMxWE5JKnXmU+
#   artifact: zip,sr,global_tool,o2pgen,lib,choco_pkg,o2p_exe   
#   force_update: true  
#   prerelease: false  
#   draft: true
#   on:    
#       SIGNING: true

# #Github odata2poco repo
# - provider: GitHub
#   auth_token:
#      secure: sB33uLo96nR+LGmYLdPmY/segb6d4O061N2e8Nbz6iyHg82D0RysMxWE5JKnXmU+
#   artifact: global_tool,o2pgen,lib,choco_pkg,o2p_exe
#   tag: $(REPO_TAG_NAME)
#   force_update: true  
#   prerelease: false  
#   repository: moh-hassan/odata2poco
#   on:    
#       SIGNING: true

# # Nuget
# - provider: NuGet
#   api_key: $(NUGET_KEY)
#   on:   
#     SIGNING: true     
#   artifact: global_tool,o2pgen,lib  

# #chocolatey    
# - provider: NuGet
#   server: https://push.chocolatey.org   
#   api_key: $(CHOCO_KEY) 
#   on:   
#     SIGNING: true    
#   artifact: choco_pkg
  
# # myget
# - provider: NuGet
#   server: https://www.myget.org/F/odata2poco/api/v3/
#   api_key: $(MYGET_KEY)
#   on:    
#     SIGNING: true      
#   artifact: global_tool,o2pgen,lib
  
  
# init:
#    - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  
# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object  net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

         