version: 1.0.0-{build}

image: Visual Studio 2022
  

build_script:
  - ps: |           
        . ./run.ps1
        Main
    
artifacts:
- path: .\*.zip
  name: zip    
- path: .\sr.txt
  name: sr    
- path: .\signed\OData2Poco.dotnet.o2pgen*.nupkg
  name: global_tool
- path: .\signed\o2pgen.exe
  name: o2p_exe
- path: .\signed\OData2Poco.CommandLine.*.nupkg
  name: o2pgen
- path: .\signed\OData2Poco.*.nupkg
  name: lib 
- path: .\signed\OData2Poco.*.snupkg
  name: symbol 
- path: .\signed\OData2Poco-CommandLine.*.nupkg
  name: choco_pkg 

 
deploy:
# Nuget
- provider: NuGet
  api_key: $(NUGET_KEY)
  artifact: global_tool,o2pgen,lib,symbol 
  on: 
    SIGNING2: true     
   

#chocolatey    
- provider: NuGet
  server: https://push.chocolatey.org   
  api_key: $(CHOCO_KEY)  
  artifact: choco_pkg
  on: 
    SIGNING2: true  
  
# myget
- provider: NuGet
  server: https://www.myget.org/F/odata2poco/api/v2/package
  api_key: $(MYGET_KEY)
  symbol_server: https://www.myget.org/F/odata2poco/symbols/api/v2/package     
  artifact: global_tool,o2pgen,lib,symbol,choco_pkg  
#  on: 
#    SIGNING2: true
    
init:
   # uncomment
   # - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  
on_finish:
  - ps: $blockRdp = $true; iex ((new-object  net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
